<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1JrnKrm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1JrnKrm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1JrnKrm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1JrnKrm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1JrnKrm\App_KernelDevDebugContainer([
    'container.build_hash' => '1JrnKrm',
    'container.build_id' => 'fe6c9322',
    'container.build_time' => 1714561812,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1JrnKrm');
