<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOss4c1l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOss4c1l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOss4c1l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOss4c1l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOss4c1l\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oss4c1l',
    'container.build_id' => '4d547424',
    'container.build_time' => 1714562011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOss4c1l');
